@tool
extends PopupPanel
class_name GDTDevMenu

var main: GodotTogether = null

func _ready() -> void:
	await get_tree().process_frame
	await get_tree().process_frame
	await get_tree().process_frame
	
	if not main:
		return
	
	fill_main()
	
	register_settings($main/scroll/vbox/logging/vbox.get_children())
	register_settings($main/scroll/vbox/settings/vbox.get_children())

func register_settings(nodes: Array) -> void:
	for i in nodes:
		if not i.has_meta("setting"):
			continue
		
		main.get_settings().make_setting_control(i, i.get_meta("setting"))

func fill_main() -> void:
	var list = $main/scroll/vbox
	
	for i in list.get_children():
		if i is FoldableContainer:
			i.fold()
			var first = i.get_child(0)
			
			if first and "main" in first:
				first.main = main

func _on_btn_node_classes_pressed() -> void:
	GDTDebug.dump_node_classes()

func _on_btn_file_tree_pressed() -> void:
	var paths = GDTFiles.get_file_tree()
	
	for i in paths:
		print(i)

func _on_btn_unsafe_file_tree_pressed() -> void:
	var paths = GDTFiles.get_file_tree("res://", true)
	
	for i in paths:
		print(i)

func _on_btn_scanned_files_pressed() -> void:
	var paths = main.file_sync.file_mod_times
	
	for i in paths:
		print(i)

func _on_btn_execute_pressed() -> void:
	var expr = Expression.new()
	var source_code = $main/scroll/vbox/exec/vbox/code.text
	var err = expr.parse(source_code)
	
	if err != OK:
		printerr(expr.get_error_text())
		return
	
	var start = Time.get_unix_time_from_system()
	var res = expr.execute([], self)
	var end = Time.get_unix_time_from_system()
	
	if not expr.has_execute_failed():
		print("Code result: %s" % res)
	
	print("Took: %s s" % str(end - start)) # why doesn't it automatically convert  to string here?

func _on_btn_alert_spam_pressed() -> void:
	for i in 1000:
		main.get_gui().alert(str(i))


func _on_btn_test_chunk_tool_script_pressed() -> void:
	# Decrease CHUNK_SIZE before using!
	var path = "res://gdt_chunk_test.gd"
	
	print("Writing %s" % path)
	
	var f = FileAccess.open(path, FileAccess.WRITE)
	
	if not f:
		printerr("Unable to open %s" % path)
		return
	
	var header = ""
	header += "# Delete this file if you see it\n"
	header += "# This is a test chunkable tool script generated by GodotTogether\n"
	header += "# It's mostly empty to test the file chunking behavior and @tool sanitization\n"
	
	if main.is_session_active():
		var user = main.dual.get_local_user()
		
		if user:
			header += "# Created by: %s (%s)\n" % [user.name, user.id]
	
	f.store_string(header)
	
	var buf = []
	
	for i in GDTFileSync.CHUNK_SIZE:
		buf.append(0xA)
		
		if i % 64:
			f.store_buffer(buf)
			buf.clear()
	
	if buf:
		f.store_string(buf)
	
	var code = ""
	code += "@tool\n"
	code += "extends Node\n"
	code += "func _ready() -> void:\n"
	code += "\tprint('Tool script triggered: %s')" % path
	
	f.store_string(code)
	f.close()
	
	print("Created %s" % path)
